N01516955_Proposal_Project1/Models/Treatment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace N01516955_Proposal_Project1.Models
{
    public class Treatment
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        //Duration is in minutes
        public int Duration { get; set; }
        //cost is in $
        public decimal Cost { get; set; }

        //list of doctors
        public ICollection<Doctor> Doctors { get; set; }
    }
    public class TreatmentDto
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
        //Duration is in minutes
        public int Duration { get; set; }
        //cost is in $
        public decimal Cost { get; set; }
        public class TreatmentViewModel
        {
            public TreatmentDto TreatmentDto { get; set; }


        }


    }

}

N01516955_Proposal_Project1/Controllers/TreatmentController.cs
using N01516955_Proposal_Project1.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using static N01516955_Proposal_Project1.Models.TreatmentDto;

namespace N01516955_Proposal_Project1.Controllers
{
    public class TreatmentController : Controller
    {
        // GET: Treatment
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static TreatmentController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44306/api/");
        }

        // GET: Treatment/Details/5
        public ActionResult List()
        {
            //objective: communicate with our animal data api to retrieve a list of animals
            //curl https://localhost:44324/api/Treatmentdata/listTreatment


            string url = "TreatmentData/ListTreatment";
            HttpResponseMessage response = client.GetAsync(url).Result;

            //Debug.WriteLine("The response code is ");
            //Debug.WriteLine(response.StatusCode);

            IEnumerable<TreatmentDto> Appointment = response.Content.ReadAsAsync<IEnumerable<TreatmentDto>>().Result;
            //Debug.WriteLine("Number of animals received : ");
            //Debug.WriteLine(animals.Count());


            return View(Appointment);
        }
        public ActionResult Details(int id)
        {


            string url = "Treatmentdata/findTreatment/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            TreatmentDto Treatment = response.Content.ReadAsAsync<TreatmentDto>().Result;

            return View(Treatment);
        }
        // GET: Treatment/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Treatment/Create
        [HttpPost]
        public ActionResult Create(Treatment treatment)
        {

            string url = "TreatmentData/addtreatment";


            string jsonpayload = jss.Serialize(treatment);

            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }


        }
        // GET: Treatment/Edit/5
        public ActionResult Edit(int id)
        {
            TreatmentViewModel treatmentviewmodel = new TreatmentViewModel();

            //the existing Doctor information
            string url = "Doctordata/findDoctor/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TreatmentDto SelectedDoctor = response.Content.ReadAsAsync<TreatmentDto>().Result;
            treatmentviewmodel.TreatmentDto = SelectedDoctor;

            return View(treatmentviewmodel);
        }

        // POST: Treatment/Edit/5
        [HttpPost]

        public ActionResult Update(int id, TreatmentViewModel treatment)
        {
            try
            {
                Treatment doc1 = new Treatment();
                doc1.Id = treatment.TreatmentDto.Id;
                doc1.Name = treatment.TreatmentDto.Name;
                doc1.Duration = treatment.TreatmentDto.Duration;
                doc1.Cost = treatment.TreatmentDto.Cost;
               

                string url = "TreatmemntData/updateTreatment/" + id;
                string jsonpayload = jss.Serialize(doc1);
                HttpContent content = new StringContent(jsonpayload);
                content.Headers.ContentType.MediaType = "application/json";
                HttpResponseMessage response = client.PostAsync(url, content).Result;

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("List");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Treatment/Delete/5
        public ActionResult DeleteConfirm(int id)
        {
            string url = "Treatmentdata/findTreatment/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TreatmentDto selectedTreatment = response.Content.ReadAsAsync<TreatmentDto>().Result;
            return View(selectedTreatment);
        }

        // POST: Doctor/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            string url = "Treatmentdata/deleteTreatment/" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

N01516955_Proposal_Project1/Views/Treatment/Create.cshtml
@model N01516955_Proposal_Project1.Models.TreatmentDto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Treatment", FormMethod.Post))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Treatment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "list")
</div>

N01516955_Proposal_Project1/Views/Treatment/DeleteConfirm.cshtml
@model N01516955_Proposal_Project1.Models.TreatmentDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>DeleteConfirm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Treatment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>
    <form action="/Treatment/Delete/@Model.Id" method="post">
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "list")
        </div>
        </form>
</div>

N01516955_Proposal_Project1/Views/Treatment/Details.cshtml
@model N01516955_Proposal_Project1.Models.TreatmentDto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Treatment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "list")
</p>

N01516955_Proposal_Project1/Views/Treatment/Edit.cshtml
@model N01516955_Proposal_Project1.Models.TreatmentDto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form action="/Treatment/Update/@Model.Id" method="POST" enctype="multipart/form-data">
    
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Treatment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    

    <div>
        @Html.ActionLink("Back to List", "list")
    </div>
</form>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

N01516955_Proposal_Project1/Views/Treatment/List.cshtml
@model IEnumerable<N01516955_Proposal_Project1.Models.TreatmentDto>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "DeleteConfirm", new { id=item.Id })
        </td>
    </tr>
}

</table>

N01516955_Proposal_Project1/Views/Treatment/New.cshtml
@model N01516955_Proposal_Project1.Models.TreatmentDto

@{
    ViewBag.Title = "New";
}

<h2>New</h2>

@using (Html.BeginForm("Create", "Treatment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Treatment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "list")
</div>